sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "YRnssek4uB908x7GzTXOeO2Zp66nx7pCrlNYfUnlpQQcVFZaPk9q14p8jp7sYyFoydIA9KPrBBbTDWKjFpRk3TJLdqpgTCmD/j4yUHs6n170MDvLXohiuoiVP41zQ8gaB1WBxXiyAyJ70kmVI7BsHAQTmZhNoASoM9wd1zXQfRU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "mDvjeyMzww8xWjUvkMeUGqFaO62L3ZPqgCru/FK5XL95mUfBTz8VXHx5lqfTvR0JALmp6PelTNglBq03R3U1Fg4IDGXxocgjHVQ1w16Nkdh0nIFt/3R46iWLZ5j7WuQTKUOzLuH/Sbk5RQybROxWbqrm/FaLP5fHk8WLnAqvTio="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="eperusteet-opintopolku"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh ${ARTIFACT_NAME}

deploy:
  - provider: script
    script: mvn deploy -pl ${ARTIFACT_NAME}-app -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
    on:
      all_branches: true