sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker


cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.cache

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "ck462fHdLrfqadVyONL/7HQGL7gdVhJ1sOmnUim3AgS3sZnCy3eadsC+mrnu8/yZcePPrXMENMAWa9E1EcmkfR2Pk5QqT2Zyc/RVAkrDm+AhsTOhejWImM/zx3LbGveOojlqTBAB0WxvEXXFRi+UkH1Y262xUMcBTsJEFfCdEbs="
    # AWS_SECRET_ACCESS_KEY
    - secure: "LjIn2YmNMm2rYH3teZ95wjELh7/8ZMALD1fPrDOQPufIx/1M0vF93rUrsoYK3hz0Daw36D9qIJbzlj3iCesjo3GEirk+pBa/LnTWX+ZtBvTXH8ITvfGGGby2MQ8MSAcmBg8gpq8P81Xie4m05k/DMgc3HG8AZy8yal9cQYNUAN4="
    - secure: "beoLQkKO0H2zqhRla3Me/epQtTkITmOpDNF1Dzd3P1e9gGGC+R36qokezAcN/l7ZCoxD19LZO/G4BCTQw8YQY8VASkLUdFgNiwtRgF1VeHkFpcebVpMTMN8p5TFA6GDMmEmh9gFCEC1U4apllQjsSPGF+e/3UaxceWNQZ/PbS8ro5H5zh/NWlUAcx0BeoKSBPAo+Q6d7gFvQ+jJw3dFXVx62LSStqGwA+mJWywhXGVouqO5DrwFVwgd/5CKDHAqbhkSeJVsqf7WSiLWVuh55iBDjQFNYevTyBsvFRnPl2khjEzHe7FdBnXDgyTQmG5s0WbkkDGmGhXyOOapDO9hdsW+O1rnjZVz1D9AoxEvP/Lw+7VWDZyqlCYDZxfPdMdM+E7+tZBLJJBS5J1aXS0/ZQm3Ps+4ZZefDLLBmqGDBs++Cymq23ubIuTAJ+4YdcUrsedKi8gjYpQPxW8bdi47k6zAxMi/OMi52poRDaGrmOj8infwglvBorMsY84oCiFvp/y70+58pZbkrosedtefHDjGFOu0X7UpYjE0MGFGayFdSkmxT9Uj6IUeSYtmSFRV95bf8uqDT22jnXSJAzdGJytzxscVEH/7tJ0uFPjTyo+985ClZOYZfEFYBRHirZrZKCtZaDF0NFg3WdqM3dmdnZy+mwr1gNk9xrGhCc9Gl7v4="
    - YLOPS_SERVICE_DIR=$PWD/eperusteet-ylops/eperusteet-ylops-service
    - EPERUSTEET_SERVICE_DIR=$PWD/eperusteet/eperusteet/eperusteet-service
    - AMOSAA_SERVICE_DIR=$PWD/eperusteet-amosaa/eperusteet-amosaa-service

install:
  - nvm install 10.16.3
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet-ylops
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet-amosaa
  - git submodule update --init --recursive

  - cd eperusteet/eperusteet && mvn dependency:resolve -B && cd ../..
  - cd eperusteet-ylops && mvn dependency:resolve -B && cd ..
  - cd eperusteet-amosaa && mvn dependency:resolve -B && cd ..

  - cd eperusteet-opintopolku-app/v2
  - yarn install

  - cd eperusteet-frontend-utils/vue
  - yarn install
  - yarn gen:api
  - rm -rf node_modules
  - cd ../../../..

  - git clone https://github.com/Opetushallitus/ci-tools.git
  - export ARTIFACT_NAME="eperusteet-opintopolku"


before_script:
  - echo $JAVA_HOME
  - java -version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


script:
  - nvm use 10.16.3
  - cd eperusteet-opintopolku-app/v2
  - yarn run lint
  - yarn run build
  - yarn run test:unit
  - cd ../..

  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - source ci-tools/common/setup-tools.sh

  - mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh ${ARTIFACT_NAME}

after_script:
  - ./cc-test-reporter format-coverage -t lcov eperusteet-opintopolku-app/v2/coverage/lcov.info
  - ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
  on:
    all_branches: true
