/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    EpAmmatillinenArvioinninKohdealueet: typeof import('./src/components/EpAmmatillinen/EpAmmatillinenArvioinninKohdealueet.vue')['default']
    EpAmmatillinenOsaalueet: typeof import('./src/components/EpAmmatillinen/EpAmmatillinenOsaalueet.vue')['default']
    EpAmmatillinenPerusteItem: typeof import('./src/components/EpAmmatillinen/EpAmmatillinenPerusteItem.vue')['default']
    EpAmmatillinenRow: typeof import('./src/components/EpAmmatillinen/EpAmmatillinenRow.vue')['default']
    EpAmmatillinenTutkinnonosaItem: typeof import('./src/components/EpAmmatillinen/EpAmmatillinenTutkinnonosaItem.vue')['default']
    EpFooter: typeof import('./src/components/EpFooter/EpFooter.vue')['default']
    EpHakutulosmaara: typeof import('./src/components/common/EpHakutulosmaara.vue')['default']
    EpHeader: typeof import('./src/components/EpHeader/EpHeader.vue')['default']
    EpJulkinenSidenav: typeof import('./src/components/EpJulkinenSidenav/EpJulkinenSidenav.vue')['default']
    EpNotificationBar: typeof import('./src/components/EpNotificationBar/EpNotificationBar.vue')['default']
    EpOpetussuunnitelmaSidenav: typeof import('./src/components/EpOpetussuunnitelmaSidenav/EpOpetussuunnitelmaSidenav.vue')['default']
    EpOpetussuunnitelmaSidenavNode: typeof import('./src/components/EpOpetussuunnitelmaSidenav/EpOpetussuunnitelmaSidenavNode.vue')['default']
    EpOpetussuunnitelmaTiedot: typeof import('./src/components/EpToteutussuunnitelma/EpOpetussuunnitelmaTiedot.vue')['default']
    EpOsaAlueListaus: typeof import('./src/components/EpToteutussuunnitelma/EpOsaAlueListaus.vue')['default']
    EpPerusteHaku: typeof import('./src/components/EpPerusteHaku.vue')['default']
    EpPerusteNotificationBar: typeof import('./src/components/EpNotificationBar/EpPerusteNotificationBar.vue')['default']
    EpPerusteRakenne: typeof import('./src/components/EpAmmatillinen/EpPerusteRakenne.vue')['default']
    EpPerusteSidenav: typeof import('./src/components/EpPerusteSidenav/EpPerusteSidenav.vue')['default']
    EpPerusteSidenavNode: typeof import('./src/components/EpPerusteSidenav/EpPerusteSidenavNode.vue')['default']
    EpPreviousNextNavigation: typeof import('./src/components/EpPreviousNextNavigation/EpPreviousNextNavigation.vue')['default']
    EpSidenavNode: typeof import('./src/components/EpSidenav/EpSidenavNode.vue')['default']
    EpSidenavNodeLabel: typeof import('./src/components/EpSidenav/EpSidenavNodeLabel.vue')['default']
    EpToteutukset: typeof import('./src/components/EpToteutussuunnitelma/EpToteutukset.vue')['default']
    EpToteutussuunnitelmaKotoLaajaAlainenOsaaminen: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaKotoLaajaAlainenOsaaminen.vue')['default']
    EpToteutussuunnitelmaKotoOpintoSisalto: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaKotoOpintoSisalto.vue')['default']
    EpToteutussuunnitelmaKoulutuksenOsa: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaKoulutuksenOsa.vue')['default']
    EpToteutussuunnitelmaKoulutuksenOsat: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaKoulutuksenOsat.vue')['default']
    EpToteutussuunnitelmaLaajaalainenOsaaminen: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaLaajaalainenOsaaminen.vue')['default']
    EpToteutussuunnitelmaOpintokokonaisuus: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaOpintokokonaisuus.vue')['default']
    EpToteutussuunnitelmaOsaamismerkki: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaOsaamismerkki.vue')['default']
    EpToteutussuunnitelmaSisaltoNimi: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaSisaltoNimi.vue')['default']
    EpToteutussuunnitelmaSuorituspolku: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaSuorituspolku.vue')['default']
    EpToteutussuunnitelmaTekstikappale: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaTekstikappale.vue')['default']
    EpToteutussuunnitelmaTiedot: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaTiedot.vue')['default']
    EpToteutussuunnitelmaTutkinnonosa: typeof import('./src/components/EpToteutussuunnitelma/EpToteutussuunnitelmaTutkinnonosa.vue')['default']
    EpTutkinnonosaNormaali: typeof import('./src/components/EpAmmatillinen/EpTutkinnonosaNormaali.vue')['default']
    EpTutkinnonosaTutke: typeof import('./src/components/EpAmmatillinen/EpTutkinnonosaTutke.vue')['default']
    EpValmaTelmaSisalto: typeof import('./src/components/EpAmmatillinen/EpValmaTelmaSisalto.vue')['default']
    GeneerinenArviointiTaulukko: typeof import('./src/components/EpAmmatillinen/GeneerinenArviointiTaulukko.vue')['default']
    PerusteRakenneOsa: typeof import('./src/components/EpAmmatillinen/PerusteRakenneOsa.vue')['default']
    RouterErrorBoundary: typeof import('./src/components/common/RouterErrorBoundary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tausta: typeof import('./src/components/EpHeader/Tausta.vue')['default']
  }
}
