export function mockRakenne() {
  return {
    'kuvaus': {
      '_tunniste': '1869c9e3-40ec-4d8d-b678-753e5c8ed80a',
      'fi': '<p>Tieto- ja tietoliikennetekniikan perustutkinnon laajuus on 180 osaamispistettä. Tutkinto muodostuu ammatillisista tutkinnon osista (145 osaamispistettä) ja yhteisistä tutkinnon osista (35 osaamispistettä). Ammatillisista tutkinnon osista pakollisia on 85—105 osaamispistettä ja valinnaisia 40—60 osaamispistettä.</p>\n\n<p>Tieto- ja tietoliikennetekniikan perustutkinnon tutkintonimikkeet ovat elektroniikka-asentaja, ICT-asentaja ja hyvinvointiteknologia-asentaja.</p>',
      'sv': '<p>Omfattningen på grundexamen i datateknik och datakommunikationsteknik är 180 kompetenspoäng. Examen består av yrkesinriktade examensdelar (145 kompetenspoäng) och gemensamma examensdelar (35 kompetenspoäng). Av de yrkesinriktade examensdelarna är 85-105 kompetenspoäng obligatoriska och 40-60 kompetenspoäng valbara.</p>\n\n<p>Examensbenämningen för grundexamen i datateknik och datakommunikationsteknik är elektronikmontör , ICT-montör och montör inom välfärdsteknik.</p>',
      'en': '<p>The scope of the vocational qualification in information and telecommunications technology is 180 competence points. The qualification is composed of vocational units (145 competence points) and common units (35 competence points). Of the vocational units, the scope of compulsory units is 85-105 competence points and the scope of optional units is 40-60 competence points.</p>\n\n<p>The qualification titles produced by the vocational qualification in information and telecommunications technology are Electronics Assembler, ICT Technician and Welfare Technology Installer.</p>',
      '_id': '6425270',
    },
    'vieras': null,
    'tunniste': 'fdacb981-0d64-4663-b91e-d106fe540e19',
    'pakollinen': false,
    'nimi': {
      '_tunniste': 'c4ab0a05-07a1-4e22-bdab-e4bb381da193',
      'sv': 'xx grundexamen',
      '_id': '3280915',
    },
    'rooli': 'määritelty',
    'muodostumisSaanto': {
      'laajuus': {
        'minimi': 180,
        'maksimi': 180,
        'yksikko': null,
      },
      'koko': null,
    },
    'osaamisala': null,
    'tutkintonimike': null,
    'osat': [
      {
        'kuvaus': null,
        'vieras': null,
        'tunniste': 'da2b0b72-4d88-49f8-84c2-16364ae00b53',
        'pakollinen': false,
        'nimi': {
          '_tunniste': '5fc7da92-0c7f-466a-888d-94c57c643163',
          'fi': 'Ammatilliset tutkinnon osat',
          'sv': 'Yrkesinriktade examensdelar',
          '_id': '3267329',
        },
        'rooli': 'määritelty',
        'muodostumisSaanto': {
          'laajuus': {
            'minimi': 145,
            'maksimi': 145,
            'yksikko': null,
          },
          'koko': null,
        },
        'osaamisala': null,
        'tutkintonimike': null,
        'osat': [
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': '3d19e1ff-c395-4e30-b85e-d414fa2654c6',
            'pakollinen': false,
            'nimi': {
              '_tunniste': 'c7abfd7a-229a-4b58-bfc3-e74e8d4fe338',
              'fi': 'Elektroniikka-asentaja',
              'sv': 'Elektronikmontör',
              '_id': '6362835',
            },
            'rooli': 'tutkintonimike',
            'muodostumisSaanto': {
              'laajuus': {
                'minimi': 105,
                'maksimi': 105,
                'yksikko': null,
              },
              'koko': null,
            },
            'osaamisala': null,
            'tutkintonimike': {
              'nimi': {
                'sv': 'Elektronikmontör',
                'fi': 'Elektroniikka-asentaja',
                'en': 'Electronics Assembler',
              },
              'arvo': '10110',
              'uri': 'tutkintonimikkeet_10110',
              'koodisto': 'tutkintonimikkeet',
              'versio': null,
            },
            'osat': [
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'fcf08e53-400d-4874-92b6-6dda1ea83f17',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': '57b1e66d-723b-48cc-b256-5b9fc61f2035',
                  'fi': 'Pakolliset tutkinnon osat',
                  'sv': 'Obligatoriska examensdelar',
                  '_id': '3267400',
                },
                'rooli': 'määritelty',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 75,
                    'maksimi': 75,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [
                  {
                    'kuvaus': null,
                    'vieras': null,
                    'tunniste': '1f48ac97-1480-403b-82fb-a4e7bfb30d95',
                    'pakollinen': true,
                    'erikoisuus': null,
                    '_tutkinnonOsaViite': '4627248',
                    'tutkinnonosa': {
                      'id': 4627248,
                      'laajuus': 45.00,
                      'jarjestys': 1,
                      '_tutkinnonOsa': '3437531',
                      'tutkinnonOsa': {
                        'id': 3437531,
                        'muokattu': 1514553740129,
                        'nimi': {
                          '_id': '488969',
                          'fi': 'Elektroniikan ja ICT:n perustehtävät',
                          'sv': 'Grunderna i elektronik och ICT',
                        },
                        'tila': 'valmis',
                        'valmis': false,
                        'osanTyyppi': 'tutkinnonosa',
                        'tyyppi': 'normaali',
                      },
                    },
                  },
                  {
                    'kuvaus': null,
                    'vieras': null,
                    'tunniste': 'dcfc24c7-5131-4b6e-abfd-555911d21632',
                    'pakollinen': true,
                    'erikoisuus': null,
                    '_tutkinnonOsaViite': '4627247',
                    'tutkinnonosa': {
                      'id': 4627247,
                      'laajuus': 30.00,
                      'jarjestys': 2,
                      '_tutkinnonOsa': '3435793',
                      'tutkinnonOsa': {
                        'id': 3435793,
                        'luotu': 1509100920117,
                        'muokattu': 1514553740131,
                        'nimi': {
                          '_id': '489343',
                          'fi': 'Ammattielektroniikka',
                          'sv': 'Yrkeselektronik',
                        },
                        'tila': 'valmis',
                        'osanTyyppi': 'tutkinnonosa',
                        'koodiArvo': '106093',
                        'tyyppi': 'normaali',
                      },
                    },
                  }],
                'versioId': null,
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '58ddb00b-2ac0-4f21-93ae-f998e3d54580',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': 'cf2ab1bd-c55a-4058-883c-0bef6e549d3f',
                  'fi': 'Valinnaiset tutkinnon osat',
                  'sv': 'Valbara examensdelar',
                  '_id': '6315247',
                },
                'rooli': 'määritelty',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 30,
                    'maksimi': 30,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [{
                  'kuvaus': null,
                  'vieras': null,
                  'tunniste': 'f6beb011-6a29-4256-9a6b-590c920bd5cf',
                  'pakollinen': false,
                  'erikoisuus': null,
                  '_tutkinnonOsaViite': '4627351',
                }, {
                  'kuvaus': null,
                  'vieras': null,
                  'tunniste': '15855379-bd58-4891-bbcf-0d42f01ca992',
                  'pakollinen': false,
                  'erikoisuus': null,
                  '_tutkinnonOsaViite': '4626773',
                }],
                'versioId': null,
              }],
            'versioId': null,
          },
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': 'd5737df9-30ff-4f9d-a2aa-b412305b7f06',
            'pakollinen': false,
            'nimi': {
              '_tunniste': 'a10f48b4-1de1-4192-8959-6c19b28dd70a',
              'fi': 'ICT-asentaja',
              'sv': 'ICT-montör',
              '_id': '6362836',
            },
            'rooli': 'tutkintonimike',
            'muodostumisSaanto': {
              'laajuus': {
                'minimi': 105,
                'maksimi': 105,
                'yksikko': null,
              },
              'koko': null,
            },
            'osaamisala': null,
            'tutkintonimike': {
              'nimi': {
                'sv': 'ICT-montör',
                'fi': 'ICT-asentaja',
                'en': 'ICT Technician',
              },
              'arvo': '10142',
              'uri': 'tutkintonimikkeet_10142',
              'koodisto': 'tutkintonimikkeet',
              'versio': null,
            },
            'osat': [{
              'kuvaus': null,
              'vieras': null,
              'tunniste': '305e1e80-dd2c-41e1-92ad-1293a6329efe',
              'pakollinen': false,
              'nimi': {
                '_tunniste': '7ce51664-e6b6-4c81-b0b4-a586d63ff448',
                'fi': 'Pakolliset tutkinnon osat',
                'sv': 'Obligatoriska examensdelar',
                '_id': '4627406',
              },
              'rooli': 'määritelty',
              'muodostumisSaanto': {
                'laajuus': {
                  'minimi': 75,
                  'maksimi': 75,
                  'yksikko': null,
                },
                'koko': null,
              },
              'osaamisala': null,
              'tutkintonimike': null,
              'osat': [{
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'd081b7bc-026f-49fa-af4e-88a0db20c399',
                'pakollinen': true,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627248',
              }, {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '0eec967b-2be0-4565-9ad4-9302e1f568f7',
                'pakollinen': true,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627245',
              }],
              'versioId': null,
            }, {
              'kuvaus': null,
              'vieras': null,
              'tunniste': 'fbd91934-ccf7-43af-bc5c-ef7eec280d5a',
              'pakollinen': false,
              'nimi': {
                '_tunniste': 'b0b93c8d-701b-458a-9556-fd5b083d4562',
                'fi': 'Valinnaiset tutkinnon osat',
                'sv': 'Valbara examensdelar',
                '_id': '6315248',
              },
              'rooli': 'määritelty',
              'muodostumisSaanto': {
                'laajuus': {
                  'minimi': 30,
                  'maksimi': 30,
                  'yksikko': null,
                },
                'koko': null,
              },
              'osaamisala': null,
              'tutkintonimike': null,
              'osat': [{
                'kuvaus': null,
                'vieras': null,
                'tunniste': '5901468d-eaaf-4442-87cf-21ae332fdb96',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626774',
              }, {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'e16a9534-b2db-4eca-8b1c-5cc6045c74b5',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627350',
              }],
              'versioId': null,
            }],
            'versioId': null,
          },
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': '2e974031-00e6-4e86-aa29-bf5896466243',
            'pakollinen': false,
            'nimi': {
              '_tunniste': 'dc1a70c6-72c4-42a8-a39c-277db38502a7',
              'fi': 'Hyvinvointiteknologia-asentaja',
              'sv': 'Montör inom välfärd',
              '_id': '6362837',
            },
            'rooli': 'tutkintonimike',
            'muodostumisSaanto': {
              'laajuus': {
                'minimi': 85,
                'maksimi': 85,
                'yksikko': null,
              },
              'koko': null,
            },
            'osaamisala': null,
            'tutkintonimike': {
              'nimi': {
                'fi': 'Hyvinvointiteknologia-asentaja',
                'sv': 'Montör inom välfärdsteknik',
                'en': 'Welfare Technology Installer',
              },
              'arvo': '01002',
              'uri': 'tutkintonimikkeet_01002',
              'koodisto': 'tutkintonimikkeet',
              'versio': null,
            },
            'osat': [{
              'kuvaus': null,
              'vieras': null,
              'tunniste': '5ef9f877-9d27-413c-bc5e-c199736def0b',
              'pakollinen': false,
              'nimi': {
                '_tunniste': '9c54796d-ed92-455a-8946-fee3b81456f8',
                'fi': 'Pakolliset tutkinnon osat',
                'sv': 'Obligatoriska examensdelar',
                '_id': '4627452',
              },
              'rooli': 'määritelty',
              'muodostumisSaanto': {
                'laajuus': {
                  'minimi': 85,
                  'maksimi': 85,
                  'yksikko': null,
                },
                'koko': null,
              },
              'osaamisala': null,
              'tutkintonimike': null,
              'osat': [{
                'kuvaus': null,
                'vieras': null,
                'tunniste': '8b83bde4-7677-4bea-80fb-81dae2fc0da9',
                'pakollinen': true,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627248',
              }, {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '386cb12e-7d18-49a0-9aa0-c53def9dfff8',
                'pakollinen': true,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627352',
              }, {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '0382c096-5075-4afd-b788-ac138f1fe620',
                'pakollinen': true,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627353',
              }],
              'versioId': null,
            }],
            'versioId': null,
          },
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': 'e3147cea-c7ea-4b46-b4a7-07498d2dfc4e',
            'pakollinen': false,
            'nimi': {
              '_tunniste': '68cda1dc-3858-4028-ae49-d292f1c4b12d',
              'fi': 'Valinnaiset tutkinnon osat',
              'sv': 'Valbara examensdelar',
              '_id': '6315460',
            },
            'rooli': 'määritelty',
            'muodostumisSaanto': {
              'laajuus': {
                'minimi': 40,
                'maksimi': 60,
                'yksikko': null,
              },
              'koko': null,
            },
            'osaamisala': null,
            'tutkintonimike': null,
            'osat': [
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'de892a08-aabf-457a-800e-06c420beff13',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627351',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '6f09aa76-a894-4eab-ac70-941ec7ba24f7',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626773',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'abd954ab-d654-4091-a9b9-b977baa9ae4f',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626774',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '04cada6b-53c8-470b-8700-b890eaa7bf12',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627350',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '559f0a2b-ec2e-4dd3-ac09-f5dfbc9f5421',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627249',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'b999edd8-24e2-4ceb-9219-cb4def533455',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627241',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '608b4850-9c9c-489e-b0db-5da1fd7a8567',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626775',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '58397378-be2c-446e-a874-03d31971ada9',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627242',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '7a4ef880-0fff-4fd0-ba33-9566ed6e16fe',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626777',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'fdd0c167-1e79-47ef-8df2-f642a79bfdb6',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627354',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'efc055bb-61d8-4d41-9801-eafb43039721',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627355',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': 'b4b12acf-6be6-4ae5-91c8-ee1120d3bb08',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627243',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '91f060d6-9850-4f73-9deb-d7bb59c30d37',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626778',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '65dbfb83-6faf-4ed8-b710-e0a746602e63',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4626776',
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '2acae468-3a44-4631-b1cc-aee931915d70',
                'pakollinen': false,
                'erikoisuus': null,
                '_tutkinnonOsaViite': '4627240',
              },
              {
                'kuvaus': {
                  '_tunniste': 'be7d5169-512d-4ba2-b085-c43e142f55e8',
                  'fi': 'Tutkinnon osa sisältää työelämän paikallisten tarpeiden mukaista osaamista, joka soveltuu useamman kuin yhden työpaikan tarpeisiin. Koulutuksen järjestäjä nimeää tutkinnon osan työelämän toimintakokonaisuuden pohjalta ja määrittää sille laajuuden osaamispisteinä. Koulutuksen järjestäjä määrittelee ammattitaitovaatimukset ja osaamisen arvioinnin vastaavasti kuin ammatillisissa tutkinnon osissa.',
                  'sv': 'Examensdelen omfattar kunnande som grundar sig arbetslivets lokala behov och som lämpar sig för fler än en arbetsplats. Utbildningsanordnaren namnger examensdelen utifrån en verksamhetshelhet i arbetslivet och fastställer omfattningen på den i kompetenspoäng. Utbildningsanordnaren fastställer kraven på yrkesskicklighet och bedömning av kunnandet på motsvarande sätt som i de yrkesinriktade examensdelarna.',
                  '_id': '3269459',
                },
                'vieras': null,
                'tunniste': '93d41c8c-884d-46cf-acc8-8d32ed44f5df',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': '04a04cb5-6efc-4cb6-ab86-88cb6e88b486',
                  'fi': 'Paikallisiin ammattitaitovaatimuksiin perustuva tutkinnon osa',
                  'sv': 'Examensdel som grundar sig på lokala krav på yrkesskicklighet',
                  '_id': '3267461',
                },
                'rooli': 'määrittelemätön',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 5,
                    'maksimi': 15,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [],
                'versioId': null,
              },
              {
                'kuvaus': {
                  '_tunniste': '7dd83e52-e55d-4b9d-b7eb-4b2fb9495f0b',
                  'fi': 'Tutkintoon voi sisällyttää tutkinnon osan toisesta ammatillisesta perustutkinnosta, ammattitutkinnosta tai erikoisammattitutkinnosta. Riippumatta sisällytettävän tutkinnon osan laajuudesta, tutkinnon osan laajuus on tässä kohdassa enintään 15 osaamispistettä.',
                  'sv': 'I examen kan ingå en examensdel från en annan yrkesinriktad grundexamen, yrkesexamen eller specialyrkesexamen. Oberoende av omfattningen på examensdelen som ska ingå utgör omfattningen på examensdelen i det här fallet högst 15 kompetenspoäng.',
                  '_id': '3267983',
                },
                'vieras': null,
                'tunniste': '0a800f1e-570c-4b09-8641-6de7551ef346',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': '7d57dbb8-21f8-4bcc-a7a8-14de20316652',
                  'fi': 'Tutkinnon osa toisesta ammatillisesta perustutkinnosta, ammattitutkinnosta tai erikoisammattitutkinnosta',
                  'sv': 'Examensdel från en annan yrkesinriktad grundexamen, yrkesexamen eller specialyrkesexamen',
                  '_id': '3267462',
                },
                'rooli': 'määrittelemätön',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 5,
                    'maksimi': 15,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [],
                'versioId': null,
              },
              {
                'kuvaus': {
                  '_tunniste': '8284beda-3d48-46a9-9d00-12e08ceccd7f',
                  'fi': 'Tutkinnon osa sisältää ammatillista osaamista tukevia korkeakouluopintoja.',
                  'sv': 'Examensdelen omfattar högskolestudier som stöder det yrkesinriktade kunnandet.',
                  '_id': '3267466',
                },
                'vieras': null,
                'tunniste': 'a06b8187-0c90-46f3-9e22-e12f8aff5f90',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': '2ffab91e-a1dd-4c57-8187-b46ff6dbbebe',
                  'fi': 'Korkeakouluopinnot',
                  'sv': 'Högskolestudier',
                  '_id': '6315242',
                },
                'rooli': 'määrittelemätön',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 5,
                    'maksimi': 15,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [],
                'versioId': null,
              },
              {
                'kuvaus': null,
                'vieras': null,
                'tunniste': '103630aa-f8d2-43a4-8ca3-74123cbb90d3',
                'pakollinen': false,
                'nimi': {
                  '_tunniste': '032399a0-b420-48cd-9b9c-f139fda18c99',
                  'fi': 'Yhteisten tutkinnon osien osa-alueita, lukio-opintoja tai muita jatko-opintovalmiuksia tukevia opintoja',
                  'sv': 'Delområden av gemensamma examensdelar, gymnasiestudier eller andra studier som stöder förutsättningarna för fortsatta studier',
                  '_id': '3267464',
                },
                'rooli': 'määrittelemätön',
                'muodostumisSaanto': {
                  'laajuus': {
                    'minimi': 1,
                    'maksimi': 25,
                    'yksikko': null,
                  },
                  'koko': null,
                },
                'osaamisala': null,
                'tutkintonimike': null,
                'osat': [],
                'versioId': null,
              }],
            'versioId': null,
          }],
        'versioId': null,
      },
      {
        'kuvaus': {
          '_tunniste': 'dd836ade-3936-43e2-bdd8-3d0d5c4ec577',
          'fi': 'Viestintä- ja vuorovaikutusosaamisen laajuus on vähintään 11 osaamispistettä, matemaattis-luonnontieteellisen osaamisen laajuus on vähintään 6 osaamispistettä ja yhteiskunta- ja työelämäosaamisen laajuus on vähintään 9 osaamispistettä. Lisäksi yhteisiin tutkinnon osiin tulee sisältyä valinnaisia osaamistavoitteita opiskelijan valitsemasta yhdestä tai useammasta yhteisestä tutkinnon osasta ja tutkinnon osan osa-alueelta tai osa-alueilta siten, että yhteisten tutkinnon osien 35 osaamispisteen laajuus täyttyy.',
          'sv': 'Kunnande i kommunikation och interaktion omfattar minst 12 kompetenspoäng, kunnande i matematik och naturvetenskap minst 6 kompetenspoäng och kunnande om samhälle och arbetsliv minst 9 kompetenspoäng. Därtill ska det i de gemensamma examensdelarna ingå valbara mål för kunnandet som den studerande väljer från en eller flera gemensamma examensdelar och ett eller flera delområden på så sätt att omfattningen på 35 kp uppfylls.',
          '_id': '6363622',
        },
        'vieras': null,
        'tunniste': '6eb0cec2-6fac-4b67-bb44-106f5c9d4f76',
        'pakollinen': false,
        'nimi': {
          '_tunniste': 'b175af77-7e97-475b-bc75-0ba485c146f9',
          'fi': 'Yhteiset tutkinnon osat',
          'sv': 'Gemensamma examensdelar',
          '_id': '3267467',
        },
        'rooli': 'määritelty',
        'muodostumisSaanto': {
          'laajuus': {
            'minimi': 35,
            'maksimi': 35,
            'yksikko': null,
          },
          'koko': null,
        },
        'osaamisala': null,
        'tutkintonimike': null,
        'osat': [
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': 'be014147-506e-4141-8d6c-2c27ce50853c',
            'pakollinen': true,
            'erikoisuus': null,
            '_tutkinnonOsaViite': '4626779',
          },
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': 'beba288b-cc2c-408d-b030-49d6dc543704',
            'pakollinen': true,
            'erikoisuus': null,
            '_tutkinnonOsaViite': '4627246',
          },
          {
            'kuvaus': null,
            'vieras': null,
            'tunniste': 'b339a7b0-62ae-4591-8ad4-12fe30639ea8',
            'pakollinen': true,
            'erikoisuus': null,
            '_tutkinnonOsaViite': '4627244',
          },
          {
            'kuvaus': {
              '_tunniste': '254f7dab-81bc-4a85-a820-344ccae4bb71',
              'fi': 'Yhteisten tutkinnon osien valinnaiset osaamistavoitteet voivat olla tutkinnon perusteissa määrättyjä tai koulutuksen järjestäjän päättämiä muita valinnaisia osaamistavoitteita, jotka tukevat kyseisen tutkinnon osan ja sen osa-alueiden tutkinnon perusteissa määrättyjä tavoitteita. Valinnaisiin osaamistavoitteisiin voidaan sisällyttää myös opiskelijan aiemmin hankkimaa osaamista, joka tukee kyseisen tutkinnon osan ja sen osa-alueiden tutkinnon perusteissa määrättyjä osaamistavoitteita.',
              'sv': 'De valbara målen för kunnandet inom de gemensamma examensdelarna omfattar 8 kp och kan vara valbara mål för kunnandet som är fastställda i examensgrunderna eller andra valbara mål som utbildningsanordnaren beslutat om och som stöder målen för kunnandet som är fastställda för den ifrågavarande examensdelen och dess delområden i examensgrunderna. I de valbara målen för kunnandet kan också ingå kunnande som den studerande förvärvat tidigare och som stöder målen för kunnandet som är fastställda för den ifrågavarande examensdelen och dess delområden i examensgrunderna.',
              '_id': '6315243',
            },
            'vieras': null,
            'tunniste': 'a9c89f0a-20b9-40cb-9660-8f6f21590f33',
            'pakollinen': false,
            'nimi': {
              '_tunniste': 'ffb20148-2960-46d6-9905-a188c668fd5b',
              'fi': 'Yhteisen tutkinnon osien valinnaiset osaamistavoitteet',
              'sv': 'Valbara mål för kunnandet inom gemensamma examensdelar (8 kp inom svenskspråkig yrkesutbildning)',
              '_id': '6315244',
            },
            'rooli': 'määrittelemätön',
            'muodostumisSaanto': {
              'laajuus': {
                'minimi': 9,
                'maksimi': 9,
                'yksikko': null,
              },
              'koko': null,
            },
            'osaamisala': null,
            'tutkintonimike': null,
            'osat': [],
            'versioId': null,
          }],
        'versioId': null,
      }],
    'versioId': 642534,
  };
}
