name: Eperusteet-opintopolku build
on: [workflow_dispatch, push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARTIFACT_NAME: eperusteet-opintopolku

jobs:
  build-and-test-eperusteet-opintopolku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Set up Node 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Print yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          yarn cache dir
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Print npm cache directory
        id: npm-cache-dir
        run: |
          npm config get cache
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Get backend eperusteet branch file http status
        id: spec_file_http_status_eperusteet
        run: |
          if [ "$(curl -s -o /dev/null -I -w '%{http_code}' https://raw.githubusercontent.com/Opetushallitus/eperusteet/${{ github.ref_name }}/generated/eperusteet.spec.json)" == "200" ] 
          then
            echo spec file found
            echo "EPERUSTEET_SPECFILE=https://raw.githubusercontent.com/Opetushallitus/eperusteet/${{ github.ref_name }}/generated/eperusteet.spec.json" >> $GITHUB_ENV
          else
            echo spec file not found
          fi
        
      - name: Get backend eperusteet-amosaa branch file http status
        id: spec_file_http_status_amosaa
        run: |
          if [ "$(curl -s -o /dev/null -I -w '%{http_code}' https://raw.githubusercontent.com/Opetushallitus/eperusteet-amosaa/${{ github.ref_name }}/generated/amosaa.spec.json)" == "200" ] 
          then
            echo spec file found
            echo "EPERUSTEET_AMOSAA_SPECFILE=https://raw.githubusercontent.com/Opetushallitus/eperusteet-amosaa/${{ github.ref_name }}/generated/amosaa.spec.json" >> $GITHUB_ENV
          else
            echo spec file not found
          fi
          
      - name: Get backend eperusteet-ylops branch file http status
        id: spec_file_http_status_ylops
        run: |
          if [ "$(curl -s -o /dev/null -I -w '%{http_code}' https://raw.githubusercontent.com/Opetushallitus/eperusteet-ylops/${{ github.ref_name }}/generated/ylops.spec.json)" == "200" ] 
          then
            echo spec file found
            echo "EPERUSTEET_YLOPS_SPECFILE=https://raw.githubusercontent.com/Opetushallitus/eperusteet-ylops/${{ github.ref_name }}/generated/ylops.spec.json" >> $GITHUB_ENV
          else
            echo spec file not found
          fi


      - name: Build eperusteet-opintopolku-ui
        run: |
          git submodule update --recursive --init
          cd eperusteet-opintopolku-app/v2
          yarn install
                    
          cd eperusteet-frontend-utils/vue
          yarn install --silent
          yarn gen:api
          rm -rf node_modules
          cd ../../../..
          
          cd eperusteet-opintopolku-app/v2
          yarn run lint
          yarn run build
          yarn run test:unit
          cd ../..

          mvn clean verify --batch-mode

      - name: Cache eperusteet-opintopolku build results
        uses: actions/cache@v3
        id: restore-build
        with:
          path: eperusteet-opintopolku-app/target
          key: ${{ github.run_number }}-${{ github.run_attempt }}-app

  build-image:
    needs: build-and-test-eperusteet-opintopolku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache eperusteet-opintopolku build results
        uses: actions/cache@v3
        id: restore-build
        with:
          path: eperusteet-opintopolku-app/target
          key: ${{ github.run_number }}-${{ github.run_attempt }}-app

      - name: Build image
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh

          mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
          cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

          export BASE_IMAGE="baseimage-war-openjdk11:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-war.sh ${ARTIFACT_NAME}
          ./ci-tools/github-build/upload-image.sh ${ARTIFACT_NAME}
